### ISSUE TITLE
Bug: ISP Report Admin

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/cmp-issues#220]
Just to say that the ISP Report Admin page is listing one report per page

**Comment by dantheta** [comment]
Fixed!  Was a little over-zealous fixing warnings and limited it to pagesize 1.

**Comment by alexhaydock** [comment]
Just to follow up on this - it seems like this problem still persists if any filter is used. The page doesn't extend beyond "1".

Fortunately it's not really an urgent problem for my current task of going through and assigning categories to anything "unassigned", though as my intent is to slowly remove everything from that category rather than browse through it.

**Edit:** I think I might be wrong that this applies to everything. This issue does still seem to be present, but only when using the "Unassigned" category that was just added to address #217

**Comment by edjw** [comment]
@dantheta – This bug is still persisting in some cases

**Comment by dantheta** [comment]
I'm seeing a full list of 25 items in unassigned, but the paging links only have one page (which I think is what Alex saw).  Should have it fixed shortly.

**Comment by dantheta** [comment]
That should be fixed now.  Its showing 98 pages with no filter applied, and 81 pages with the (unassigned) filter applied.

**Comment by alexhaydock** [comment]
> That should be fixed now. Its showing 98 pages with no filter applied, and 81 pages with the (unassigned) filter applied.

Thanks! Yep, looks like this has fixed the issue I was seeing.

**Comment by edjw** [comment]
Can we close this?
